export const GET_MARKET_DATA = "GET_MARKET_DATA";
export const ADD_FAVORITE_ASSET = "ADD_FAVORITE_ASSET";
export const REMOVE_FAVORITE_ASSET = "REMOVE_FAVORITE_ASSET";
export const ADD_BAD_ASSET = "ADD_BAD_ASSET";
export const REMOVE_BAD_ASSET = "REMOVE_BAD_ASSET";